class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start5'
        self.MirrorCommand = 'dl5'
        self.UnzipMirrorCommand = 'unzip5'
        self.TarMirrorCommand = 'tar5'
        self.ZipMirrorCommand = 'zip5'
        self.CancelMirror = 'batal5'
        self.CancelAllCommand = 'batalin5'
        self.ListCommand = 'cari5'
        self.StatusCommand = 'status5'
        self.AuthorizedUsersCommand = 'users5'
        self.AuthorizeCommand = 'auth5'
        self.UnAuthorizeCommand = 'unauth5'
        self.AddSudoCommand = 'addsudo5'
        self.RmSudoCommand = 'rmsudo5'
        self.PingCommand = 'ping5'
        self.RestartCommand = 'restart5'
        self.StatsCommand = 'stat5'
        self.HelpCommand = 'bantuan5'
        self.LogCommand = 'log5'
        self.SpeedCommand = 'speedtest5'
        self.CloneCommand = 'salin5'
        self.CountCommand = 'hitung5'
        self.WatchCommand = 'watch5'
        self.TarWatchCommand = 'tarwatch5'
        self.DeleteCommand = 'del5'
        self.ConfigMenuCommand = 'config5'
        self.ShellCommand = 'shell5'
        self.UpdateCommand = 'update5'
        self.ExecHelpCommand = 'exechelp5'
        self.TsHelpCommand = 'tshelp5'

BotCommands = _BotCommands()
