class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start6'
        self.MirrorCommand = 'dl6'
        self.UnzipMirrorCommand = 'unzip6'
        self.TarMirrorCommand = 'tar6'
        self.ZipMirrorCommand = 'zip6'
        self.CancelMirror = 'batal6'
        self.CancelAllCommand = 'batalin6'
        self.ListCommand = 'cari6'
        self.StatusCommand = 'status6'
        self.AuthorizedUsersCommand = 'users6'
        self.AuthorizeCommand = 'auth6'
        self.UnAuthorizeCommand = 'unauth6'
        self.AddSudoCommand = 'addsudo6'
        self.RmSudoCommand = 'rmsudo6'
        self.PingCommand = 'ping6'
        self.RestartCommand = 'restart6'
        self.StatsCommand = 'stat6'
        self.HelpCommand = 'bantuan6'
        self.LogCommand = 'log6'
        self.SpeedCommand = 'speedtest6'
        self.CloneCommand = 'salin6'
        self.CountCommand = 'hitung6'
        self.WatchCommand = 'watch6'
        self.TarWatchCommand = 'tarwatch6'
        self.DeleteCommand = 'del6'
        self.ConfigMenuCommand = 'config6'
        self.ShellCommand = 'shell6'
        self.UpdateCommand = 'update6'
        self.ExecHelpCommand = 'exechelp6'
        self.TsHelpCommand = 'tshelp6'

BotCommands = _BotCommands()
